### ISSUE TITLE
Cant find device Rointe Thermostat device CT2

### ISSUE THREAD

**Issue by polpas** [tggm/rointe-hacs#16]
Hi,

I have a Roite CT2 WiFi Thermostat that is detected as described in the log but does not appear.

2024-06-04 14:01:52.939 ERROR (MainThread) [custom_components.rointe] Unexpected error fetching rointe data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/coordinator.py", line 44, in _async_update_data
    new_devices = await self.device_manager.update()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 179, in update
    new_device = await self._process_api_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 225, in _process_api_data
    new_device = self._add_or_update_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 285, in _add_or_update_device
    rointe_device = RointeDevice(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 73, in __init__
    self.update_data(device_info, energy_data, latest_fw)
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 102, in update_data
    self.um_max_temp = float(data["um_max_temp"])
                             ~~~~^^^^^^^^^^^^^^^
KeyError: 'um_max_temp'
2024-06-04 14:02:03.310 DEBUG (MainThread) [custom_components.rointe] Device manager updating
2024-06-04 14:02:03.617 DEBUG (MainThread) [custom_components.rointe] Found device ID: xxxxxxxxxxxxxxxxxx0610
2024-06-04 14:02:04.261 DEBUG (MainThread) [custom_components.rointe] Processing data for device ID: 4CAA441C06104CAA441C0610
2024-06-04 14:02:04.261 DEBUG (MainThread) [custom_components.rointe] Found new device CT.2 1C0610 [therm] - v2. FW: 2_1_1
2024-06-04 14:02:04.262 ERROR (MainThread) [custom_components.rointe] Unexpected error fetching rointe data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/coordinator.py", line 44, in _async_update_data
    new_devices = await self.device_manager.update()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 179, in update
    new_device = await self._process_api_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 225, in _process_api_data
    new_device = self._add_or_update_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 285, in _add_or_update_device
    rointe_device = RointeDevice(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 73, in __init__
    self.update_data(device_info, energy_data, latest_fw)
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 102, in update_data
    self.um_max_temp = float(data["um_max_temp"])
                             ~~~~^^^^^^^^^^^^^^^
KeyError: 'um_max_temp'
2024-06-04 14:02:04.263 DEBUG (MainThread) [custom_components.rointe] Finished fetching rointe data in 0.953 seconds (success: False)


Can you check what may be wrong?

**Comment by ikk0** [comment]
Same issue here. Would love to see support for the CT2. Let us know how we can help! :)

**Comment by sebastian-enz** [comment]
Submitted a PR for rointe-sdk which fixes this, then CT.2 thermostats appear in HA: https://github.com/tggm/rointe-sdk/pull/10

**Comment by tggm** [comment]
Please reopen if it still happens after version 2.0.0
