### ISSUE TITLE
Failed setup: retry 'schedule_day' error

### ISSUE THREAD

**Issue by paissad** [tggm/rointe-hacs#17]
Hi,

I have the following errors while using the integration. It's my first time using this integration.
I am using the version **1.4.3**
Here is what I get with the debug logs enabled!
Any help would be appreciated.
I also saw this discussion into the HA community site https://community.home-assistant.io/t/rointe-heaters-integration/758330/1 

The device seems to be found! --> `Towel F9D108 [oval_towel]`

```
2024-10-01 17:28:21.407 DEBUG (MainThread) [custom_components.rointe] Finished fetching rointe data in 0.929 seconds (success: False)
2024-10-01 17:28:41.904 DEBUG (MainThread) [custom_components.rointe] Device manager updating
2024-10-01 17:28:42.261 DEBUG (MainThread) [custom_components.rointe] Found device ID: B8E2CAF9D108B8E2CAF9D108
2024-10-01 17:28:42.868 DEBUG (MainThread) [custom_components.rointe] Processing data for device ID: B8E2CAF9D108B8E2CAF9D108
2024-10-01 17:28:42.869 DEBUG (MainThread) [custom_components.rointe] Found new device Towel F9D108 [oval_towel] - v2. FW: 2_1_1
2024-10-01 17:28:42.869 ERROR (MainThread) [custom_components.rointe] Unexpected error fetching rointe data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/coordinator.py", line 44, in _async_update_data
    new_devices = await self.device_manager.update()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 179, in update
    new_device = await self._process_api_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 225, in _process_api_data
    new_device = self._add_or_update_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rointe/device_manager.py", line 285, in _add_or_update_device
    rointe_device = RointeDevice(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 73, in __init__
    self.update_data(device_info, energy_data, latest_fw)
  File "/usr/local/lib/python3.12/site-packages/rointesdk/device.py", line 110, in update_data
    self.schedule_day = data["schedule_day"]
                        ~~~~^^^^^^^^^^^^^^^^
KeyError: 'schedule_day'
```

**Comment by Infeconex** [comment]
Adding I'm also affected by this. I want to use this integration to trigger heating control when I'm leaving or arriving home.

**Comment by Kaeroe** [comment]
Having the same issue, only after removing and adding a new radiator (warranty repair)
There was a firmware update to the radiators very recently, I think to 2.1.3
Could that have changed something to alter the key name so now it cannot be referenced?

**Comment by Hethemaniac** [comment]
Having the same issue after adding a new radiator to the instalation.
Would be wonderful to have some patch :)

**Comment by Infeconex** [comment]
@tggm - from what I can see on the HA forum, Rointe don't want to support firmware downgrades, or engaging with the home assistant community. Is there any help you can provide on this breaking change?

**Comment by tggm** [comment]
I'll try to fix this issue in the next release

**Comment by Kaeroe** [comment]
> I'll try to fix this issue in the next release

2.0.0-1 fixes this, thank you ever so much!

**Comment by Hethemaniac** [comment]
Thank you so much for real!

**Comment by Infeconex** [comment]
Thank you. Have you got a “buy me a coffee” type link? I appreciate you’re doing this in your spare time.

On 10 Jan 2025, at 20:18, tggm ***@***.***> wrote:

﻿


Closed #17 as completed.

**Comment by tggm** [comment]
Thank you for your kind words @Infeconex  :) 

I do now! It's on the Readme: https://buymeacoffee.com/tggm

**Comment by Hethemaniac** [comment]
Any wallet I can tip u?

**Comment by tggm** [comment]
Thank you @Hethemaniac  :) you mean crypto wallet? I can do that, which coin?

**Comment by Hethemaniac** [comment]
Anything u want via arb or solana chains :)

**Comment by tggm** [comment]
Here you go: 0x0165C7afd359B85a6F7f1D22d6EC7FB183f3b446

Thank you once again 🙏

**Comment by Infeconex** [comment]
Is this all fixed now?

**Comment by paissad** [comment]
> Is this all fixed now?

Yes it is 🙏🏾
